language: javascript
node_js:
  - "iojs"
  - "8"

cache:
  directories:
    - "node_modules"

install:
   - yarn install

jobs:
  include:
    - stage: 'lint'
      script: yarn run lint
    - state: 'test'
      script: yarn run test
    - stage: 'build'
      script: yarn build
