language: javascript
node_js:
  - "iojs"
  - "8"

cache:
  directories:
    - "node_modules"

install:
   - npm install
   - yarn install

jobs:
  include:
    - stage: 'lint'
      script: npm run lint
    - stage: 'build'
      script: npm build
